M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 09, 2023 at 15:51:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-09T15:51:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X6.1059Y-5.9988
X6.3335Y-5.9988
T2
X5.73Y-4.3352
X5.73Y-5.5352
X6.93Y-4.3352
X6.93Y-5.5352
T0
M30
